name: release
on:
  push:
    tags:
      - 'v*'
      
jobs:
  build-to-release:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: microsoft/setup-msbuild@v2.0.0

      - name: Build
        run: .\BuildReleaseApplication.bat

      - name: Zip
        run: |
          powershell Compress-Archive bin\Release\net6.0-windows\win-x64\publish\* LiveFrame.zip

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ github.ref_name }}
          files: |
            LiveFrame.zip
          prerelease: true
          draft: false
