name: release
on:
  push:
    tags:
      - 'v*'
      
jobs:
  build-to-release:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: microsoft/setup-msbuild@v2.0.0

      - name: Extract version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Build
        run: |
          dotnet restore
          dotnet publish --runtime win-x64 --configuration Release --self-contained false --property:Version=${{ env.VERSION }}

      - name: Zip
        run: |
          powershell Compress-Archive bin\Release\net6.0-windows\win-x64\publish\* LiveFrame.zip

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ github.ref_name }}
          files: |
            LiveFrame.zip
          prerelease: true
          draft: false
