name: check build
on:
  push:
    branches:
      - master
jobs:
  check-build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: microsoft/setup-msbuild@v2.0.0
      - run: .\BuildReleaseApplication.bat
