name: check build
on: [push]
jobs:
  check-build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: microsoft/setup-msbuild@v1.0.2
      - run: .\BuildReleaseApplication.bat
