name: check pullrequest build
on:
  pull_request:
    types: [opened, synchronize]
jobs:
  check-build-for-pull-request:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: microsoft/setup-msbuild@v1.0.2
      - run: .\BuildReleaseApplication.bat
